### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by floatinghotpot** [sunnycupertino/cordova-plugin-admob-simple#1]
As this project is totally copied from my project, without any actual improvement: 
cordova-plugin-admob

Hope you can mention it in Credits.

**Comment by sunnycupertino** [comment]
Hi Raymond. We did use it as a template, but your project actually didn't work on either iOS or Android, we have done a lot of work on it since then, so it in't true that it is completely copied and without improvement. It also used (at the time we checked) an old version of the iOS libraries, so we completely replaced them. After replacing them we had to change a lot of code, not to mention rewrite the cordova iOS plugin initialization, etc. Also we stabilized and simplified it's operation in Android. We will put something in the credits though, thank you for what you provided.
