### ISSUE TITLE
SDK versions

### ISSUE THREAD

**Issue by Guivagu-zz** [sunnycupertino/cordova-plugin-admob-simple#12]
After include this plugin in the project, build android with cordova. I got problems to run on Android 5.0 but works ok on Android 6.0
Is it possible that plugin only works in recent android versions?

Thanks for the plugin!!

**Comment by sunnycupertino** [comment]
Hi Guivagu. Our plugin works well with all Android versions. Can you tell me:
-What error is on the console when you run it and it crashes?
-What studio do you use to develop? Android Studio or Eclipse.
-Are you sure the error is caused by the plugin. For example if you uninstall the plugin and comment out the plugin code, does the app work again?

**Comment by Guivagu-zz** [comment]
I have been checking and it is not a problem of the plugin, because commenting the lines that use de plugin the app still does not work. I will be working on it.

Thanks for the support!

**Comment by sunnycupertino** [comment]
Ok Guivagu no problem. We have tested it on all platforms possible and it works well, admob ads showing. Let me know if you have any more questions.
